name: "JS CodeQL analysis"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - 'static/**.js'
      - 'Dockerfile'
      - 'docker-compose.yml'

jobs:
  analyze_js:
    name: Analyze code
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
